### ISSUE TITLE
cannot install react-stacked-center-carousel

### ISSUE THREAD

**Issue by simonsrour** [BotDanny/react-stacked-center-carousel#10]
I am getting the following error in the terminal

npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: new-dp@0.1.0
npm ERR! Found: react-dom@18.1.0
npm ERR! node_modules/react-dom
npm ERR!   peer react-dom@"^17.0.0 || ^18.0.0" from @mui/material@5.8.3
npm ERR!   node_modules/@mui/material
npm ERR!     peer @mui/material@"^5.0.0" from @mui/icons-material@5.8.3
npm ERR!     node_modules/@mui/icons-material
npm ERR!       @mui/icons-material@"^5.4.1" from react-material-ui-carousel@3.4.2
npm ERR!       node_modules/react-material-ui-carousel
npm ERR!       1 more (the root project)
npm ERR!     @mui/material@"^5.4.1" from react-material-ui-carousel@3.4.2
npm ERR!     node_modules/react-material-ui-carousel
npm ERR!     1 more (the root project)
npm ERR!   peer react-dom@"^17.0.0 || ^18.0.0" from @mui/base@5.0.0-alpha.84
npm ERR!   node_modules/@mui/material/node_modules/@mui/base
npm ERR!     @mui/base@"5.0.0-alpha.84" from @mui/material@5.8.3
npm ERR!     node_modules/@mui/material
npm ERR!       peer @mui/material@"^5.0.0" from @mui/icons-material@5.8.3
npm ERR!       node_modules/@mui/icons-material
npm ERR!         @mui/icons-material@"^5.4.1" from react-material-ui-carousel@3.4.2
npm ERR!         node_modules/react-material-ui-carousel
npm ERR!         1 more (the root project)
npm ERR!       2 more (react-material-ui-carousel, the root project)
npm ERR!   7 more (@testing-library/react, framer-motion, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! react-stacked-center-carousel@"*" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: react-dom@18.2.0
npm ERR! node_modules/react-dom
npm ERR!   peer react-dom@"^18.2.0" from react-stacked-center-carousel@1.0.11
npm ERR!   node_modules/react-stacked-center-carousel
npm ERR!     react-stacked-center-carousel@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See C:\Users\Simon\AppData\Local\npm-cache\eresolve-report.txt for a full report.

**Comment by BotDanny** [comment]
Hi Simon, is this likely due to conflicting peer dependency: react-dom@18.2.0. I will update react-stacked-center-carousel's peer dependency to support any version greater than version 14.

**Comment by BotDanny** [comment]
Hi Simon, a new version with updated peer dependency is published. Please update react-stacked-center-carousel to version 1.0.12
