### ISSUE TITLE
How to use StackedCarouselSlideProps

### ISSUE THREAD

**Issue by dat0825** [BotDanny/react-stacked-center-carousel#14]
I read document, but i don't understand what is `StackedCarouselSlideProps`? and how to use it?
I think `const Slide = React.memo(function (props: StackedCarouselSlideProps) ` is failed syntax in reactjs

**Comment by BotDanny** [comment]
`StackedCarouselSlideProps` is the typescript interface that contains all the fields that will be passed to your slide component. You need to use typescript, and `const Slide = React.memo(function (props: StackedCarouselSlideProps) {return null})` Should work
