### ISSUE TITLE
Objects are not valid as a React child  in react-stacked-center-carousel

### ISSUE THREAD

**Issue by asadali012** [BotDanny/react-stacked-center-carousel#20]
I am using react-stacked-center-carousel and the code is defined in
https://codesandbox.io/s/elegant-snowflake-k3rf75?file=/src/App.js

now when i pass an array of objects to <StackedCeraousel />
this gives an error

Objects are not valid as a React child (found: object with keys {$$typeof, type, compare}). If you meant to render a collection of children, use an array instead.

As i am defining data as an array

**Comment by BotDanny** [comment]
Hi, please post a codesandbox link to reproduce the error. I don't see any issue with the codesandbox you provided.

**Comment by asadali012** [comment]
> Hi, please post a codesandbox link to reproduce the error. I don't see any issue with the codesandbox you provided.

https://codesandbox.io/s/sad-dirac-ptfl8z?file=/src/App.js

This is the sandbox with the issue

**Comment by BotDanny** [comment]
Hi, you exported your slide component using named export, but you imported your slide component as default import. Change your slide component import from `import Slide from "../components/Slide";` to `import {Slide} from "../components/Slide";` then it will work. The carousel itself has no issue.

**Comment by asadali012** [comment]
@BotDanny Resolved
ThankYou
