### ISSUE TITLE
Broken in iOS 11, 12, 13 after updating react-resize-detector from 5.2 to version 6.6 

### ISSUE THREAD

**Issue by lan0105** [BotDanny/react-stacked-center-carousel#3]
I have a problem with lib react-resize-detector:
_After we updated to 6.6 users on iOS 11-13 get an error undefined is not a constructor, evaluating new window.ResizeObserver(n.resizeHandler)_
Expect: 
This issue still exists in latest version 6.7.6 as well.
[var reactResizeDetector = require('react-resize-detector/build/withPolyfill');](url)
Please update, many thanks!!!!
https://github.com/maslianok/react-resize-detector/issues/141#issuecomment-951084148

**Comment by BotDanny** [comment]
Updated to latest verison
